finalsanber/routes/admin.php
<?php


use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('dashboard');

Route::get('/author/data', 'DataController@authors')->name('author.data');
Route::get('/book/data', 'DataController@books')->name('book.data');
Route::get('/borrow/data', 'DataController@borrows')->name('borrow.data');

Route::resource('author', 'AuthorController');
Route::resource('book', 'BookController');
Route::resource('users', 'UserController');

Route::get('export', 'MyController@export')->name('export');
Route::get('export/user', 'MyController@exportUsers')->name('export.user');

Route::get('importExportView', 'MyController@importExportView');
Route::post('import', 'MyController@import')->name('import');

Route::get('borrow', 'BorrowController@index')->name('borrow.index');

Route::put('borrow/{borrowHistory}/return', 'BorrowController@returnBook')->name('borrow.return');



// Route::get('/author', 'AuthorController@index')->name('author.index');

// Route::get('/author/create', 'AuthorController@create')->name('author.create');

// Route::post('/author', 'AuthorController@store')->name('author.store');

// Route::get('/author/{author}/edit', 'AuthorController@edit')->name('author.edit');

// Route::put('/author/{author}', 'AuthorController@update')->name('author.update');

// Route::delete('/author/{author}', 'AuthorController@destroy')->name('author.destroy');

finalsanber/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\\BookController@index')->name('homepage');

Route::get('/user/home', 'HomeController@index')->name('home');

Route::post('/book/{book}/borrow', 'FrontEnd\\BookController@borrow')->name
('book.borrow')->middleware('auth');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

finalsanber/app/Book.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $guarded = [];

    public function author()
    {
        return $this->belongsTo(Author::class);
    }

    public function getCover()
    {
        if(substr($this->cover,0,5) == "https") {
            return $this->cover;
        }

        if($this->cover){
            return asset($this->cover);
        }

        return 'https://via.placeholder.com/150x200.png?text=No+Cover';
    }

    public function borrowed()
    {
        return $this->belongsToMany(User::class, 'history');
    }
}

finalsanber/app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Author;
use App\Book;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.book.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.book.create', [
            'authors' => Author::orderBy('name', 'ASC')->get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required|min:20',
            'author_id' => 'required',
            'cover' => 'required|image',
            'quantity' => 'required|numeric'
        ]);

        if($request->hasFile('cover')) {
            $cover = $request->file('cover')->store('assets/covers');
        }

        Book::create([
            'title' => $request->title,
            'description' => $request->description,
            'author_id' => $request->author_id,
            'cover' => $cover,
            'quantity' => $request->quantity,
        ]);

        return redirect()->route('admin.book.index')->with('success', 'Data buku berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        return view('admin.book.edit', [
            'book' => $book,
            'authors' => Author::orderBy('name', 'ASC')->get(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required|min:20',
            'author_id' => 'required',
            'cover' => 'required|image',
            'quantity' => 'required|numeric'
        ]);

        $cover = $book->cover;

        if($request->hasFile('cover')) {
            Storage::delete($book->cover);
            $cover = $request->file('cover')->store('assets/covers');
        }

        $book->update([
            'title' => $request->title,
            'description' => $request->description,
            'author_id' => $request->author_id,
            'cover' => $cover,
            'quantity' => $request->quantity,
        ]);

        return redirect()->route('admin.book.index')->with('info', 'Data buku berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();

        return redirect()->route('admin.book.index')
            ->with('danger', 'Data buku berhasil dihapus.');
    }
}

finalsanber/app/Http/Controllers/Frontend/BookController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Book;
use App\BorrowHistory;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BookController extends Controller
{
    public function index()
    {
        $books = Book::orderBy('created_at', 'DESC')->limit(1)->get();
        return view('frontend.templates.master', [
            'books' => $books,
        ]);
    }

    public function show(Book $book)
    {
        return view('frontend.book.show', [
            'book' => $book
        ]);
    }

    public function borrow(Book $book)
    {
        $user = auth()->user();

        if($user->borrow()->isStillBorrow($book->id)) {
            return redirect()->back()->with('danger', 'Kamu sudah memimnjam buku dengan judul ini!');
        }

        $user->borrow()->attach($book);
        $book->decrement('quantity');

        return redirect()->back()->with('success', 'Berhasil meminjam buku');
    }
}

finalsanber/resources/views/admin/book/action.blade.php
<a href="{{ route('admin.book.edit', $model) }}" class="btn btn-warning btn-sm mr-2">Edit</a>
<button href="{{ route('admin.book.destroy', $model) }}" class="btn btn-danger btn-sm mr-2"
    id="delete">Delete</button>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>

<script>
    $('button#delete').on('click', function(e) {
        e.preventDefault();

        var href =  $(this).attr('href');

        Swal.fire({
            title: 'Apakah Anda yakin hapus data ini?',
            text: "Data yang sudah dihapus tidak dapat dikembalikan!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, hapus!'
            }).then((result) => {
            if (result.isConfirmed) {

                document.getElementById('deleteForm').action = href;
                document.getElementById('deleteForm').submit();

                Swal.fire(
                'Terhapus!',
                'Data berhasil dihapus!',
                'success'
                )
            }
        })

    })
</script>

finalsanber/resources/views/admin/book/create.blade.php
@extends('admin.templates.master')

@section('content')
    <h3>Add new Book</h3>
<form role="form" action="{{ route('admin.book.store') }}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="card-body">

        <div class="form-group @error('title') 'has-error' @enderror">
            @error('title')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="title">Judul</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ old('title') }}" placeholder="Masukkan judul Buku..">
        </div>

        <div class="form-group @error('description') 'has-error' @enderror">
            @error('description')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="description">Description</label><br>
            <textarea name="description" class="form-control" id="description" cols="30" rows="3" placeholder="Masukkan deskripsi buku..">
                {{ old('description') }}
            </textarea>
        </div>

        <div class="form-group @error('author_id') 'has-error' @enderror">
            @error('author_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="author_id">Author</label><br>
            <select name="author_id" id="author_id" class="form-control select2">
                @foreach ($authors as $author)
                    <option value="{{ $author->id }}">{{ $author->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group @error('cover') 'has-error' @enderror">
            @error('cover')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="cover">Sampul Buku</label>
            <input type="file" name="cover" class="form-control">
        </div>

        <div class="form-group @error('quantity') 'has-error' @enderror">
            @error('quantity')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="quantity">Jumlah</label>
            <input type="text" class="form-control" name="quantity" id="quantity" value="{{ old('quantity') }}" placeholder="Masukkan jumlah buku..">
        </div>

        <button type="submit" class="btn btn-primary">Tambah Buku</button>

    </div>
    <!-- /.card-body -->
</form>
@endsection

@push('select2css')
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2/css/select2.min.css') }}">
@endpush

@push('data-tables')
    <script src="{{ asset('assets/plugins/select2/js/select2.full.min.js') }}"></script>

    <script>
        $(['.select2'].select2();)
    </script>
@endpush

finalsanber/resources/views/admin/book/edit.blade.php
@extends('admin.templates.master')

@section('content')
    <h3>Edit Data Book</h3>
<form role="form" action="{{ route('admin.book.update', $book) }}" method="post" enctype="multipart/form-data">
    @csrf
    @method("PUT")
    <div class="card-body">

        <div class="form-group @error('title') 'has-error' @enderror">
            @error('title')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="title">Judul</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ $book->title ?? old('title') }}" placeholder="Masukkan judul Buku..">
        </div>

        <div class="form-group @error('description') 'has-error' @enderror">
            @error('description')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="description">Description</label><br>
            <textarea name="description" class="form-control" id="description" cols="30" rows="3" placeholder="Masukkan deskripsi buku..">
                {{ $book->description ?? old('description') }}
            </textarea>
        </div>

        <div class="form-group @error('author_id') 'has-error' @enderror">
            @error('author_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="author_id">Author</label><br>
            <select name="author_id" id="author_id" class="form-control select2">
                @foreach ($authors as $author)
                    <option
                        value="{{ $author->id }}"
                        @if ($author->id === $book->author_id)
                            selected
                        @endif
                    >
                        {{ $author->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group @error('cover') 'has-error' @enderror">
            @error('cover')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="cover">Sampul Buku</label>
            <input type="file" name="cover" class="form-control">
        </div>

        <div class="form-group @error('quantity') 'has-error' @enderror">
            @error('quantity')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="quantity">Jumlah</label>
            <input type="text" class="form-control" name="quantity" id="quantity" value="{{ $book->quantity ?? old('quantity') }}" placeholder="Masukkan jumlah buku..">
        </div>

        <button type="submit" class="btn btn-primary">Edit</button>

    </div>
    <!-- /.card-body -->
</form>
@endsection

@push('select2css')
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2/css/select2.min.css') }}">
@endpush

@push('data-tables')
    <script src="{{ asset('assets/plugins/select2/js/select2.full.min.js') }}"></script>

    <script>
        $(['.select2'].select2();)
    </script>
@endpush

finalsanber/resources/views/admin/book/index.blade.php
@extends('admin.templates.master')

@section('item-active')
<a href="{{ route('admin.book.index') }}">Book</a>
@endsection

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Data Book</h3>
            <a class="btn btn-primary" href="{{ route('admin.book.create') }}">Add new book</a>
            <a href="{{ route('admin.export.user') }}" class="btn btn-success my-3" target="_blank">Export to Excel</a>
            <br>
        </div>

        <div class="box-body">
            <br>
            @include('admin.templates.partials.alerts')
            <table id="dataTable" class="table table-bordered table-hover">

                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Judul</th>
                        <th>Deskripsi</th>
                        <th>Jumlah Buku</th>
                        <th>Author</th>
                        <th>Sampul Buku</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>

        </div>

    </div>

    <form action="" method="post" id="deleteForm">
        @csrf
        @method("DELETE")
        <input type="submit" value="Delete" class="btn btn-danger btn-sm mr-2" style="display: none;">
    </form>

@endsection

@push('data-tables')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>

    <script>
        $(function() {
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('admin.book.data') }}',
                columns: [
                    { data: 'DT_RowIndex', orderable: false, searchable:
                    false},
                    { data: 'title'},
                    { data: 'description'},
                    { data: 'quantity'},
                    { data: 'author'},
                    { data: 'cover'},
                    { data: 'action'}
                ]
            });
        });
    </script>
@endpush