finalsanber/routes/admin.php
<?php


use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('dashboard');

Route::get('/author/data', 'DataController@authors')->name('author.data');
Route::get('/book/data', 'DataController@books')->name('book.data');
Route::get('/borrow/data', 'DataController@borrows')->name('borrow.data');

Route::resource('author', 'AuthorController');
Route::resource('book', 'BookController');
Route::resource('users', 'UserController');

Route::get('export', 'MyController@export')->name('export');
Route::get('export/user', 'MyController@exportUsers')->name('export.user');

Route::get('importExportView', 'MyController@importExportView');
Route::post('import', 'MyController@import')->name('import');

Route::get('borrow', 'BorrowController@index')->name('borrow.index');

Route::put('borrow/{borrowHistory}/return', 'BorrowController@returnBook')->name('borrow.return');



// Route::get('/author', 'AuthorController@index')->name('author.index');

// Route::get('/author/create', 'AuthorController@create')->name('author.create');

// Route::post('/author', 'AuthorController@store')->name('author.store');

// Route::get('/author/{author}/edit', 'AuthorController@edit')->name('author.edit');

// Route::put('/author/{author}', 'AuthorController@update')->name('author.update');

// Route::delete('/author/{author}', 'AuthorController@destroy')->name('author.destroy');

finalsanber/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\\BookController@index')->name('homepage');

Route::get('/user/home', 'HomeController@index')->name('home');

Route::post('/book/{book}/borrow', 'FrontEnd\\BookController@borrow')->name
('book.borrow')->middleware('auth');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

finalsanber/app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    protected $guarded = [];

    public $timestamps = false;

    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

finalsanber/app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Author;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\AuthorExport;
use App\Http\Controllers\Controller;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.author.index');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.author.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:5'
        ]);
        Author::create($request->only('name'));

        return redirect()->route('admin.author.index')->with('success', 'Data author berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Author $author)
    {
        return view('admin.author.edit', [
            'author' => $author,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Author $author)
    {
        $this->validate($request, [
            'name' => 'required|min:5'
        ]);

        $author->update($request->only('name'));

        return redirect()->route('admin.author.index')->with('info', 'Data author berhasil diupdate.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Author $author)
    {
        $author->delete();

        return redirect()->route('admin.author.index')
            ->with('danger', 'Data author berhasil dihapus.');
    }

    public function export_excel()
	{
		return Excel::download(new AuthorsExport, 'author.xlsx');
	}
}

finalsanber/resources/views/admin/author/action.blade.php
<a href="{{ route('admin.author.edit', $model) }}" class="btn btn-warning btn-sm mr-2">Edit</a>
<button href="{{ route('admin.author.destroy', $model) }}" class="btn btn-danger btn-sm mr-2"
    id="delete">Delete</button>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>

<script>
    $('button#delete').on('click', function(e) {
        e.preventDefault();

        var href =  $(this).attr('href');

        Swal.fire({
            title: 'Apakah Anda yakin hapus data ini?',
            text: "Data yang sudah dihapus tidak dapat dikembalikan!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, hapus!'
            }).then((result) => {
            if (result.isConfirmed) {

                document.getElementById('deleteForm').action = href;
                document.getElementById('deleteForm').submit();

                Swal.fire(
                'Terhapus!',
                'Data berhasil dihapus!',
                'success'
                )
            }
        })

    })
</script>

finalsanber/resources/views/admin/author/create.blade.php
@extends('admin.templates.master')

@section('content')
    <h3>Add new Author</h3>
<form role="form" action="{{ route('admin.author.store') }}" method="post">
    @csrf
    <div class="card-body">
        <div class="form-group @error('name') 'has-error' @enderror">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="name">Nama</label>
            <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}" placeholder="Masukkan nama Author..">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    <!-- /.card-body -->
</form>
@endsection

finalsanber/resources/views/admin/author/edit.blade.php
@extends('admin.templates.master')

@section('content')
    <h3>Edit Data Author</h3>
<form role="form" action="{{ route('admin.author.update', $author) }}" method="post">
    @csrf
    @method("PUT")
    <div class="card-body">
        <div class="form-group @error('name') 'has-error' @enderror">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="name">Nama</label>
            <input type="text" class="form-control" name="name" id="name"
            value="{{ old('name') ?? $author->name }}" placeholder="Masukkan nama Author..">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Edit</button>
    </div>
    <!-- /.card-body -->
</form>
@endsection

finalsanber/resources/views/admin/author/import.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 5.7 Import Export Excel to database Example - ItSolutionStuff.com</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
</head>
<body>

<div class="container">
    <div class="card bg-light mt-3">
        <div class="card-header">
            Export to Excel
        </div>
        <div class="card-body">
            <form action="{{ route('admin.import') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <input type="file" name="file" class="form-control">
                <br>
                <button class="btn btn-success">Import User Data</button>
                <a class="btn btn-warning" href="{{ route('admin.export') }}">Export User Data</a>
            </form>
        </div>
    </div>
</div>
</body>
</html>

finalsanber/resources/views/admin/author/index.blade.php
@extends('admin.templates.master')

@section('item-active')
<a href="{{ route('admin.author.index') }}">Author</a>
@endsection

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Data Authors</h3>
            <a class="btn btn-primary" href="{{ route('admin.author.create') }}">Add new author</a>
            <a href="{{ route('admin.export') }}" class="btn btn-success my-3" target="_blank">Export to Excel</a>
            <br>
        </div>

        <div class="box-body">
            <br>
            @include('admin.templates.partials.alerts')
            <table id="dataTable" class="table table-bordered table-hover">

                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nama</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>

        </div>

    </div>

    <form action="" method="post" id="deleteForm">
        @csrf
        @method("DELETE")
        <input type="submit" value="Delete" class="btn btn-danger btn-sm mr-2" style="display: none;">
    </form>

@endsection

@push('data-tables')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>

    <script>
        $(function() {
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('admin.author.data') }}',
                columns: [
                    { data: 'DT_RowIndex', orderable: false, searchable:
                    false},
                    { data: 'name'},
                    { data: 'action'}
                ]
            });
        });
    </script>
@endpush