finalsanber/routes/admin.php
<?php


use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('dashboard');

Route::get('/author/data', 'DataController@authors')->name('author.data');
Route::get('/book/data', 'DataController@books')->name('book.data');
Route::get('/borrow/data', 'DataController@borrows')->name('borrow.data');

Route::resource('author', 'AuthorController');
Route::resource('book', 'BookController');
Route::resource('users', 'UserController');

Route::get('export', 'MyController@export')->name('export');
Route::get('export/user', 'MyController@exportUsers')->name('export.user');

Route::get('importExportView', 'MyController@importExportView');
Route::post('import', 'MyController@import')->name('import');

Route::get('borrow', 'BorrowController@index')->name('borrow.index');

Route::put('borrow/{borrowHistory}/return', 'BorrowController@returnBook')->name('borrow.return');



// Route::get('/author', 'AuthorController@index')->name('author.index');

// Route::get('/author/create', 'AuthorController@create')->name('author.create');

// Route::post('/author', 'AuthorController@store')->name('author.store');

// Route::get('/author/{author}/edit', 'AuthorController@edit')->name('author.edit');

// Route::put('/author/{author}', 'AuthorController@update')->name('author.update');

// Route::delete('/author/{author}', 'AuthorController@destroy')->name('author.destroy');

finalsanber/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\\BookController@index')->name('homepage');

Route::get('/user/home', 'HomeController@index')->name('home');

Route::post('/book/{book}/borrow', 'FrontEnd\\BookController@borrow')->name
('book.borrow')->middleware('auth');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

finalsanber/app/Http/Controllers/Admin/BorrowController.php
<?php

namespace App\Http\Controllers\Admin;

use App\BorrowHistory;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;

class BorrowController extends Controller
{
    public function index()
    {
        return view('admin.borrow.index');
    }

    public function returnBook(Request $request, BorrowHistory $borrowHistory)
    {
        $borrowHistory->update([
            'returned_at' => Carbon::now(),
            'admin_id' => auth()->id(),
        ]);

        $borrowHistory->book()->increment('quantity');

        return redirect()->back()->with('success', 'Buku dikembalikan');
    }
}

finalsanber/resources/views/admin/borrow/action.blade.php
<button href="{{ route('admin.borrow.return', $model) }}" class="btn btn-info btn-sm mr-2"
    id="return">Pengembalian Buku</button>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <script>
        $('button#return').on('click', function(e) {
            e.preventDefault();

            var href =  $(this).attr('href');

            Swal.fire({
                title: 'Apakah Anda ingin mengembalikan buku ini?',
                text: "Konfirmasi data & buku yang dikembalikan sama!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, benar. Data sudah diperiksa!'
                }).then((result) => {
                if (result.isConfirmed) {

                    document.getElementById('returnForm').action = href;
                    document.getElementById('returnForm').submit();

                    Swal.fire(
                    'Dikembalikan!',
                    'Buku dikembalikan!',
                    'success'
                    )
                }
            })

        })
    </script>

finalsanber/resources/views/admin/borrow/create.blade.php
@extends('admin.templates.master')

@section('content')
    <h3>Add new Author</h3>
<form role="form" action="{{ route('admin.author.store') }}" method="post">
    @csrf
    <div class="card-body">
        <div class="form-group @error('name') 'has-error' @enderror">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="name">Nama</label>
            <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}" placeholder="Masukkan nama Author..">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    <!-- /.card-body -->
</form>
@endsection

finalsanber/resources/views/admin/borrow/edit.blade.php
@extends('admin.templates.master')

@section('content')
    <h3>Edit Data Author</h3>
<form role="form" action="{{ route('admin.author.update', $author) }}" method="post">
    @csrf
    @method("PUT")
    <div class="card-body">
        <div class="form-group @error('name') 'has-error' @enderror">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <label for="name">Nama</label>
            <input type="text" class="form-control" name="name" id="name"
            value="{{ old('name') ?? $author->name }}" placeholder="Masukkan nama Author..">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Edit</button>
    </div>
    <!-- /.card-body -->
</form>
@endsection

finalsanber/resources/views/admin/borrow/index.blade.php
@extends('admin.templates.master')

@section('item-active')
<a href="{{ route('admin.author.index') }}">Peminjaman</a>
@endsection

@section('content')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Data Peminjaman Buku</h3>
        </div>

        <div class="box-body">
            <br>
            @include('admin.templates.partials.alerts')
            <table id="dataTable" class="table table-bordered table-hover">

                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nama</th>
                        <th>Judul Buku</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>

        </div>

    </div>

    <form action="" method="post" id="returnForm">
        @csrf
        @method("PUT")
        <input type="submit" value="Return" class="btn btn-danger btn-sm mr-2" style="display: none;">
    </form>

@endsection

@push('data-tables')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>

    <script>
        $(function() {
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('admin.borrow.data') }}',
                columns: [
                    { data: 'DT_RowIndex', orderable: false, searchable:
                    false},
                    { data: 'user'},
                    { data: 'book_title'},
                    { data: 'action'}
                ]
            });
        });
    </script>
@endpush